//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientAndProviders.Web.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientShiftAssignment
    {
        public int ClientId { get; set; }
        public string DayOfWeek { get; set; }
        public string Shift { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
