//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientAndProviders.Web.Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClientsProvidersDbEntities : DbContext
    {
        public ClientsProvidersDbEntities()
            : base("name=ClientsProvidersDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<SvcCode> SvcCodes { get; set; }
        public virtual DbSet<WeekDay> WeekDays { get; set; }
        public virtual DbSet<WorkShift> WorkShifts { get; set; }
        public virtual DbSet<ClientShiftAssignment> ClientShiftAssignments { get; set; }
        public virtual DbSet<ClientSvcCode> ClientSvcCodes { get; set; }
        public virtual DbSet<ProviderAvailableShift> ProviderAvailableShifts { get; set; }
        public virtual DbSet<ProviderSvcCode> ProviderSvcCodes { get; set; }
        public virtual DbSet<ProviderAndProviderAvailableShift> ProviderAndProviderAvailableShifts { get; set; }
    }
}
