//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientAndProviders.Web.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvcCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SvcCode()
        {
            this.ClientSvcCodes = new HashSet<ClientSvcCode>();
            this.ProviderSvcCodes = new HashSet<ProviderSvcCode>();
        }
    
        public string SvcCodeValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientSvcCode> ClientSvcCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderSvcCode> ProviderSvcCodes { get; set; }
    }
}
